"""`docs`: keep the md/ folder in step with the code, and show where the notes think we are versus where the code is.
Writes md/STATE.md (live facts) and md/COMMANDS.md (every command), and `docs --check` prints the differences."""
import glob
import json
import os
import re
import subprocess
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MD = os.path.join(ROOT, "md")

COMMAND_HELP = {
    "init": "create the database", "mock": "load an offline demo market", "sde": "import game data from a file",
    "scan": "rank everything you can do now (add --live to download prices)", "plan": "same as scan, no download",
    "watch": "keep re-scanning", "profile": "set system/cargo in the profile", "login": "log a character in (once per character)",
    "sync": "read skills, wallet, assets, location from the game", "log": "enter a timed run by hand",
    "go": "send the route of a ranked task to the game client", "universe": "load the map and items",
    "esimap": "build a map from ESI around you", "fleet": "list parked ships", "skills": "ISK/hr-measured skill advice + training plan",
    "diag": "check the game data", "explain": "why an item ranks where it does", "check": "re-check live prices of a ranked task",
    "stock": "value of everything you own", "along": "sell on the way to a destination", "fit": "what is fitted to your ship",
    "zkill": "refresh the hauler-loss map", "next": "ONE next step (agent offers, sell/list, best trade)", "keep": "build or sell your materials",
    "bpbuy": "buy a blueprint to use your stock?", "update": "has a game patch changed the data?", "bestprice": "best buyers for one item anywhere",
    "sellplan": "sell/list/carry/detour/haul per stack", "day": "chain the best tasks for N hours", "now": "sync + scan + next step + price check",
    "chars": "compare your characters", "combatfit": "set real DPS/EHP/tank for combat", "journey": "plan a whole trip with pickups and trades",
    "compare": "list here or make the trip?", "start": "start timing an activity", "stop": "stop timing, read payouts and loot, log it",
    "pause": "freeze the running timer", "resume": "unfreeze it", "trainplan": "what to train now/next", "activities": "all timed runs",
    "status": "where data is stored, row counts", "docs": "refresh md/STATE.md and md/COMMANDS.md; --check shows doc/code drift",
    "fixlast": "correct the last timed run (--add-min N, --isk N)",
}


def code_commands():
    s = open(os.path.join(ROOT, "eve_profit", "cli.py"), encoding="utf-8").read()
    return re.findall(r'"(\w+)"', re.search(r'choices=\[([^\]]*)\]', s).group(1))


def git(*args):
    try:
        return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, timeout=20).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return ""


def count_tests():
    n = 0
    for f in glob.glob(os.path.join(ROOT, "tests", "test_*.py")):
        n += len(re.findall(r"^\s+def test_", open(f, encoding="utf-8").read(), re.M))
    return n


def gather(con=None, db_path=""):
    d = {"when": time.strftime("%Y-%m-%d %H:%M"), "branch": git("rev-parse", "--abbrev-ref", "HEAD"), "commit": git("log", "--oneline", "-1"),
         "dirty": [l for l in git("status", "--short").splitlines() if l.strip()], "commands": code_commands(), "tests": count_tests(),
         "db": db_path, "session": None, "agent_offers": None, "runs": []}
    if con is not None:
        try:
            r = con.execute("SELECT value FROM meta WHERE key='session'").fetchone()
            if r:
                d["session"] = json.loads(r[0])
            d["runs"] = [dict(x) for x in con.execute("SELECT activity,isk,hours,ship,ts FROM activity_log ORDER BY ts DESC LIMIT 8")]
        except Exception:
            pass
    f = os.path.join(ROOT, "agent_offers.json")
    if os.path.exists(f):
        try:
            offers = json.load(open(f, encoding="utf-8")).get("offers", [])
            d["agent_offers"] = [o["agent"].split(" (")[0] + ": " + o["mission"][:60] for o in offers if o.get("available", True)]
        except (ValueError, KeyError):
            pass
    return d


def write(d):
    os.makedirs(MD, exist_ok=True)
    L = ["# STATE (auto-generated by `python -m eve_profit docs` - do not edit by hand)", "",
         "(No timestamps or commit ids here on purpose: this file only changes when the real state changes. "
         "Uncommitted files and the last commit are shown by `docs --check` and `git status`.)",
         f"Branch `{d['branch']}` | tests defined: {d['tests']} | commands in code: {len(d['commands'])}", ""]
    if d["agent_offers"]:
        L.append("\nOpen agent offers (agent_offers.json):")
        L += [f"- {x}" for x in d["agent_offers"]]
    open(os.path.join(MD, "STATE.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    # per-PC facts (timer, timed runs) go to a git-ignored file so the tracked notes never differ between machines
    L = ["# LOCAL STATE (this PC only, git-ignored, auto-generated by `docs`)", ""]
    if d["session"]:
        s = d["session"]
        L.append(f"\nTimer RUNNING: '{s['activity']}' since {time.strftime('%H:%M', time.localtime(s['t']))}"
                 + (" (PAUSED: run `python -m eve_profit resume`)" if s.get("pause_t") else "") + ". Finish with `python -m eve_profit stop`.")
    else:
        L.append("\nNo timer running.")
    if d["runs"]:
        L.append("\nLatest timed runs:")
        L += [f"- {time.strftime('%m-%d %H:%M', time.localtime(r['ts']))} {r['activity']}: {r['isk']:,.0f} ISK in {r['hours'] * 60:.0f} min ({r['isk'] / max(r['hours'], 1e-9):,.0f} ISK/hr) {r['ship'] or ''}" for r in d["runs"]]
    open(os.path.join(MD, "LOCAL_STATE.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    C = ["# COMMANDS (auto-generated; run each as `python -m eve_profit <command>`)", ""]
    C += [f"- `{c}` - {COMMAND_HELP.get(c, '(no description yet)')}" for c in d["commands"]]
    C += ["", "Scripts: `python scripts/agent_steps.py [next|list|done|skip|back|reset]` - Level 1 agent checklist."]
    open(os.path.join(MD, "COMMANDS.md"), "w", encoding="utf-8").write("\n".join(C) + "\n")


def check(d):
    """-> list of differences between what the notes say and what the code is."""
    out = []
    missing = [c for c in d["commands"] if c not in COMMAND_HELP]
    if missing:
        out.append(f"commands in code with no description in docs.py: {', '.join(missing)}")
    extra = [c for c in COMMAND_HELP if c not in d["commands"]]
    if extra:
        out.append(f"commands described in docs.py but not in the code: {', '.join(extra)}")
    for f in sorted(glob.glob(os.path.join(MD, "*.md")) + [os.path.join(ROOT, "README.md")]):
        if os.path.basename(f) in ("STATE.md", "COMMANDS.md"):
            continue
        text = open(f, encoding="utf-8").read()
        for m in re.finditer(r"(\d+) (?:unit )?tests", text):
            if int(m.group(1)) != d["tests"] and int(m.group(1)) > 20:
                out.append(f"{os.path.basename(f)} says {m.group(1)} tests, code has {d['tests']}")
        for c in set(re.findall(r"python -m eve_profit (\w+)", text)):
            if c not in d["commands"] and c not in ("x",):
                out.append(f"{os.path.basename(f)} mentions `{c}`, which is not a command in the code")
    if d["dirty"]:
        out.append(f"{len(d['dirty'])} uncommitted file(s): the notes on GitHub may be behind what is on disk")
    if d["session"] and d["session"].get("pause_t"):
        out.append("a timer is PAUSED: the code is waiting for `resume`")
    return sorted(set(out))
